name: zyrealm

services:
  zyrealm:
    image: ghcr.io/mumu-140/zyrealm:v0.11.0-mumu.10
    pull_policy: never
    container_name: zyrealm
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      OCTOPUS_SERVER_HOST: 0.0.0.0
      OCTOPUS_SERVER_PORT: "35276"
